server:
  port: 8081

spring:
  application:
    name: orders-reactive

  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:orders_db}?useServerPrepareStatement=true&serverZoneId=UTC
    username: ${DB_USERNAME:orders_user}
    password: ${DB_PASSWORD:orders_pass}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework.r2dbc: DEBUG

email:
  smtp:
    host: ${EMAIL_SMTP_HOST:smtp.gmail.com}
    port: ${EMAIL_SMTP_PORT:587}
    username: ${EMAIL_SMTP_USERNAME:}
    password: ${EMAIL_SMTP_PASSWORD:}
    api-key: ${EMAIL_SMTP_API_KEY:}
    use-ssl: ${EMAIL_SMTP_USE_SSL:false}
    use-starttls: ${EMAIL_SMTP_USE_STARTTLS:true}
  from: ${EMAIL_FROM:orders@company.com}
